### ISSUE TITLE
Question: Clarify the purpose of Reaper

### ISSUE THREAD

**Issue by brandonbowersox** [gofullstack/reaper#1]
Hi Mike,

Harvest can export IIF files using the TIMEACT format to import to Quickbooks. So is Reaper's purpose to re-format that same data so it generates an IIF file containing Quickbooks invoices (TRANS SPL ENDTRNS) instead of TIMEACT?

Harvest IIF docs here: http://help.getharvest.com/harvest/integrations/accounting-integrations/quickbooks/

Thanks in advance for any clarification you can provide.

-Brandon

**Comment by joshcramer** [comment]
@brandonbowersox your second sentence is close. The purpose of Reaper is to pull invoice data (not time data) out of Harvest and import it into Quickbooks. Once the import is complete, you end up with invoices in Quickbooks that match the invoices that you created in Harvest.

The existing Harvest Quickbooks integration supports only raw time records, so that you would only end up with time data in Quickbooks. With this approach, you would still need to create the invoices in the Quickbooks program.

Reaper allows you to create the invoices in Harvest based on time entries that were made in Harvest and then to export the resulting invoices to Quickbooks.

Hopefully that clarifies.

**Comment by brandonbowersox** [comment]
That clarifies it well! Thanks!
